### ISSUE TITLE
This item node will not run

### ISSUE THREAD

**Issue by SunOfHomeBoy** [yyc-git/WebGPU-RTX#7]
![image](https://user-images.githubusercontent.com/30047595/236751194-1db936a1-67e7-4151-8099-dcc53a9920a3.png)

Please explain the running steps in detail in readme

**Comment by yyc-git** [comment]
该项目暂时不要运行

具体运行环境详见

https://www.cnblogs.com/chaogex/p/13199224.html#%E6%90%AD%E5%BB%BA%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83

用第2种方法来搭建运行环境

另外，
刚刚有同学发布了webrtx，可以将我们之前写WebGPU Node代码，运行在Chrome上
具体详见：
https://github.com/codedhead/webrtx

**Comment by SunOfHomeBoy** [comment]
> 该项目暂时不要运行
> 
> 具体运行环境详见
> 
> https://www.cnblogs.com/chaogex/p/13199224.html#%E6%90%AD%E5%BB%BA%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83
> 
> 用第2种方法来搭建运行环境
> 
> 另外， 刚刚有同学发布了webrtx，可以将我们之前写WebGPU Node代码，运行在Chrome上 具体详见： https://github.com/codedhead/webrtx

感谢赐教
